.eslintrc, .gitignore, dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, package.json, src/App/index.jsx, src/Button/Button.jsx, src/Button/e-button.scss, src/Button/example.jsx, src/Header/Header.jsx, src/Header/e-header.scss, src/Header/example.jsx, src/Toggler/Toggler.jsx, src/Toggler/e-toggler.scss, src/Toggler/example.jsx, src/styles/index.scss, src/styles/mixins/icons.scss, src/utils/index.js, webpack.config.js, yarn.lock
https://jira.railsc.ru/browse/GOODS-411
=> feature(eti): Добавит компоненты, пофиксит билд

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/ComboSelect/ComboSelect.jsx, src/Header/Header.jsx, src/Pagination/Pagination.jsx, src/Toggler/Toggler.jsx, src/export.js
Смотри еще этот коммент https://github.com/abak-press/apress-tiger/pull/2#pullrequestreview-27911411
=> Сейчас пагинатор точно нормально экспортится из node_modules

dist/app.bundle.js, dist/assets-table.bundle.js, src/Button/Button.jsx, src/CheckCell/CheckCell.jsx, src/HeaderCell/HeaderCell.jsx, src/ImageCell/ImageCell.jsx, src/PathCell/PathCell.jsx, src/Row/Row.jsx, src/Table/Table.jsx, src/TextCell/TextCell.jsx
=> fix: добавлен реакт импорт

.eslintrc, dist/app.bundle.js, dist/assets-table.bundle.js, index.html, src/App/App.jsx, src/Button/example.jsx, src/ComboSelect/example.jsx, src/Header/example.jsx, src/Pagination/example.jsx, src/Table/example.jsx, src/index.js, src/reducers.js, src/store.js
Должно быть теперь все гуд вообще
=> fix Нормальный билд

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, package.json, src/ActionsPanel/ActionsPanel.jsx, src/ActionsPanel/e-actions-panel.scss, src/ActionsPanel/example.jsx, src/App/App.jsx, src/App/style.scss, src/Button/e-button.scss, src/ComboSelect/ComboSelect.jsx, src/Scroller/Scroller.jsx, src/Scroller/e-scroller.scss, src/Scroller/example.jsx, src/Table/e-table.scss, src/Toggler/e-toggler.scss, src/styles/mixins/icons.scss, src/styles/mixins/index.scss, yarn.lock
https://jira.railsc.ru/browse/GOODS-438
=> feature(tiger): Добавит новые компоненты

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, package.json, src/Actions/Actions.jsx, src/Actions/e-actions.scss, src/Actions/example.jsx, src/App/App.jsx, src/App/style.scss, src/Checkbox/Checkbox.jsx, src/Checkbox/e-checkbox.scss, src/Checkbox/example.jsx, src/ComboSelect/ComboSelect.jsx, src/ComboSelect/e-select.scss, src/DropDownMenu/DropDownMenu.jsx, src/DropDownMenu/e-dropdown-menu.scss, src/DropDownMenu/example.jsx, src/Pagination/Pagination.jsx, src/Table/Header.jsx, src/Table/e-table.scss, src/export.js, src/styles/global.scss, src/styles/mixins/icons.scss, webpack.config.js, yarn.lock
https://jira.railsc.ru/browse/GOODS-463
=> feature(triger): Добавит компоненты Checkbox, Actions, починит селект

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/FloatPanel/e-float-panel.scss, src/Header/e-header.scss, src/Table/Header.jsx, src/Table/e-table.scss, src/Tree/Tree.jsx, src/Tree/e-tree.scss, src/Tree/reducer.js
https://jira.railsc.ru/browse/GOODS-488
=> fix: мелкие правки

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/Table/Text.jsx, src/Table/actions.js, src/Table/e-table.scss, src/Table/reducerRow.js, src/Table/reducers/selected.js, src/export.js, src/reducers.js
https://jira.railsc.ru/browse/GOODS-486
=> feature(tiger): Протягивание текстовых ячеек

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, package.json, src/App/style.scss, src/Table/Body.jsx, src/Table/Check.jsx, src/Table/Image.jsx, src/Table/Path.jsx, src/Table/Table.jsx, src/Table/Text.jsx, src/Table/actions.js, src/Table/e-table.scss, src/Table/example.jsx, src/Table/reducers/focus.js, src/export.js, src/reducers.js, src/store.js, src/utils/validation.js, yarn.lock
https://jira.railsc.ru/browse/GOODS-497
=> feature(tiger): Управление таблицей

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, server.js, src/ActionsPanel/e-actions-panel.scss, src/App/sagas.js, src/Filter/actions.js, src/Filter/reducer.js, src/Help/Help.jsx, src/Help/sagas.js, src/SaveControl/SaveControl.jsx, src/Table/e-table.scss, src/Table/reducers/history.js, src/Tree/ContainerTree.jsx, src/Tree/Tree.jsx, src/Tree/TreeItem.jsx, src/Tree/import.js, src/Tree/reducer.js, src/Tree/sagas.jsx, src/_app.mock.js, src/exportHelp.js
https://jira.railsc.ru/browse/GOODS-416
https://jira.railsc.ru/browse/GOODS-542
https://jira.railsc.ru/browse/GOODS-570
=> feature: спаравка, фильтр по ид, ограничение истори

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/Tree/Tree.jsx
https://jira.railsc.ru/browse/GOODS-503
=> fix: tree dnd

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/Tree/Tree.jsx, src/Tree/TreeItem.jsx, src/Tree/reducer.js, src/Tree/sagas.jsx
https://jira.railsc.ru/browse/GOODS-503
=> fix: правки перетаскивания в рубрикаторе

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/RemoveConfirmationDialog/RemoveConfirmationDialog.jsx, src/RemoveEmptyGroupsDialog/RemoveEmptyGroupsDialog.jsx, src/remove/sagas.js
https://jira.railsc.ru/browse/GOODS-526
=> fix(Front-end): Починит закрытие модальников

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/App/style.scss, src/Tree/ContainerTree.jsx, src/Tree/e-tree.scss, src/Tree/import.js, src/styles/global.scss
https://jira.railsc.ru/browse/GOODS-594
=> feature: поиск в рубрикаторе

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, package.json, src/ImageEditor/ImageEditor.jsx, yarn.lock
https://jira.railsc.ru/browse/GOODS-615
=> fix(front-end) Дополнительная валидация в зоне дропа

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/Dialog/rc-dialog.scss, src/ImageEditor/ImageEditor.jsx, src/ImageEditor/e-image-editor.scss
https://jira.railsc.ru/browse/GOODS-589
=> fix(front-end): Доработки

.gitignore, dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, package.json, src/Button/__tests__/Button.js, src/Button/__tests__/__snapshots__/Button.js.snap, src/ImageEditor/__tests__/actions.js, src/ImageEditor/__tests__/reducer.js, src/ImageEditor/__tests__/saga.js, src/_app.mock.js, test/setup.js, yarn.lock
Заготовка на обсуждение.
ссылки по теме 
https://facebook.github.io/jest/
https://github.com/airbnb/enzyme
https://hackernoon.com/testing-react-components-with-jest-and-enzyme-41d592c174f
http://redux.js.org/docs/recipes/WritingTests.html
https://youtu.be/59Ndb3YkLKA
=> Зачатки тестов

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/Filter/reducer.js
https://jira.railsc.ru/browse/GOODS-633
=> fix: сброс пагинатора при фильтре по группе

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, server.js, src/App/App.jsx, src/App/sagas.js, src/FloatPanel/FloatPanel.jsx, src/FloatPanel/e-float-panel.scss, src/SwitchCategory/SetItem.jsx, src/SwitchCategory/SwitchCategory.jsx, src/SwitchCategory/__tests__/actions.js, src/SwitchCategory/__tests__/reducer.js, src/SwitchCategory/actions.js, src/SwitchCategory/e-switch-cat-menu.scss, src/SwitchCategory/e-switch-category.scss, src/SwitchCategory/e-switch-tooltip.scss, src/SwitchCategory/example.js, src/SwitchCategory/reducer.js, src/SwitchCategory/sagas.js, src/_app.mock.js, src/export.js, src/reducers.js
https://jira.railsc.ru/browse/GOODS-639
=> feature(front-end): переключение режимов групп/категорий

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, package.json, src/App/App.jsx, src/Button/Button.jsx, src/ImageEditor/__tests__/saga.js, src/SaveControl/SaveControl.jsx, src/SaveControl/SaveControlContainer.jsx, src/SaveControl/__tests__/SaveControl.js, src/SaveControl/__tests__/__snapshots__/SaveControl.js.snap, src/SaveControl/__tests__/actions.js, src/SaveControl/__tests__/reducer.js, src/SaveControl/reducer.js, src/SaveControl/sagas.js, src/export.js, src/store.js
https://jira.railsc.ru/browse/GOODS-600
=> feature: правка багов неявного удаления

README.md, dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, package.json, src/SwitchCategory/SetItem.jsx, src/SwitchCategory/__tests__/SetItem.js, src/SwitchCategory/__tests__/SwitchCategory.js, src/SwitchCategory/__tests__/__snapshots__/SetItem.js.snap, src/SwitchCategory/__tests__/__snapshots__/SwitchCategory.js.snap, test/test-utils.js
Sagas are hard, testing them is even harder (Napoleon)
=> feature(front-end) Добавлены тесты

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/Tree/e-tree.scss
https://jira.railsc.ru/browse/GOODS-679
=> fix(front-end): Починит скролл в навигации

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/SwitchCategory/e-switch-tooltip.scss
https://jira.railsc.ru/browse/GOODS-680
=> fix(front-end): Правки по подсказке переключения групп.

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/Filter/sagas.js
https://jira.railsc.ru/browse/GOODS-743
=> fix: не открывается ссылка на ТИГР с меткой в Близко

src/ActionsPanel/ActionsPanel.jsx, src/Table/Price.jsx, src/Tree/ContainerTree.jsx, src/Tree/Tree.jsx
https://jira.railsc.ru/browse/GOODS-302
=> fix: [skip ci]

src/SaveControl/__tests__/reducer.js, src/SaveControl/reducer.js, src/Table/reducers/history.js, src/Table/rowReducer.js
https://jira.railsc.ru/browse/GOODS-835
=> fix(SaveControl): починит добавление группы при несохраненом родителе

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js
https://jira.railsc.ru/browse/GOODS-836
=> feature: добавит возможность копирования групп, bundles

dist/app.bundle.js, dist/assets-table.bundle.js, src/ActionsPanel/ActionsPanel.jsx, src/Table/Body.jsx, src/Table/Text.jsx
https://jira.railsc.ru/browse/GOODS-302
=> fix: Сопутствующие товары

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/SaveControl/__tests__/reducer.js, src/SaveControl/__tests__/sagas.js, src/SaveControl/reducer.js, src/SaveControl/sagas.js, src/Table/__tests__/actions.js, src/Table/__tests__/reducers/history.js, src/Table/__tests__/rowReducer.js, src/Table/__tests__/tableReducer.js, src/Table/actions.js, src/Table/reducers/history.js, src/Table/rowReducer.js, src/Table/tableReducer.js, test/__tests__/testUtils.js, test/testUtils.js
https://jira.railsc.ru/browse/GOODS-912
=> feature: добавит возможность изменения url группы при редактировании

src/utils/__tests__/utils.js, src/utils/index.js
https://jira.railsc.ru/browse/GOODS-912
=> fix: исправит ошибку при протягивании картинки

src/Table/e-table.scss, src/components/Table/__tests__/TextCellEditor.js, src/components/Table/containers/TextCellEditor.js
https://jira.railsc.ru/browse/GOODS-871
=> fix: исправит ошибки при вставке текста в текстовые поля

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css
https://jira.railsc.ru/browse/GOODS-871
=> fix: исправит ошибки при вставке текста в текстовые поля, bundles

dist/app.bundle.js, dist/assets-table.bundle.js, src/Table/rowReducer.js
https://jira.railsc.ru/browse/GOODS-912
=> fix: починит отмену действия при протягивании картинки

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/Table/e-table.scss, src/Table/rowReducer.js, src/components/Table/__tests__/TextCellEditor.js, src/components/Table/containers/TextCellEditor.js
https://jira.railsc.ru/browse/GOODS-871
=> fix: обрезает лишние символы при вставке в текстовые поля

dist/app.bundle.js, dist/assets-table.bundle.js, src/components/Table/containers/TextCellEditor.js
https://jira.railsc.ru/browse/GOODS-871
=> fix: починит ошибку с возвратом старого значения при клике по полю ввода

src/Table/CheckRelatedProducts.js, src/Table/Price.jsx
https://jira.railsc.ru/browse/GOODS-952
=> fix(related products): увеличит кол-во соп. товаров, исправит вывод цены

dist/app.bundle.js, dist/assets-table.bundle.js
https://jira.railsc.ru/browse/GOODS-1014
=> chore: bundles

dist/app.bundle.js, dist/assets-table.bundle.js, src/ActionsPanel/ActionsPanel.jsx, src/Tree/ContainerTree.jsx
https://jira.railsc.ru/browse/GOODS-1020
=> fix: исправит вывод иконки настройки в списке групп

src/Table/Text.jsx
https://jira.railsc.ru/browse/GOODS-1022
=> feature: добавит редактирование выделенной ячейки по нажатию клавиш

dist/app.bundle.js, dist/assets-table.bundle.js, src/Table/Text.jsx
https://jira.railsc.ru/browse/GOODS-1022
=> fix: поправит написание в выделенную ячейку по нажатию клавиш

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/remove/sagas.js
https://jira.railsc.ru/browse/GOODS-700
=> fix: починит удаление несохраненных групп при массовом удалении

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/Table/Body.jsx, src/Table/Image.jsx, src/Table/Table.jsx, src/Table/Text.jsx, src/Table/e-table.scss, src/components/Table/containers/TextCellEditor.js, src/components/Table/views/DragTool.js, src/components/Table/views/EditControlPanel.js, src/components/Table/views/TouchEditTool.js, src/styles/mixins/icons.scss, src/utils/index.js
https://jira.railsc.ru/browse/GOODS-1030
=> feature: возможность редактирования ячеек в моб. версии [skip ci]

.eslintrc, dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/App/sagas.js, src/SaveControl/__tests__/reducer.js, src/SaveControl/reducer.js, src/Table/Table.jsx, src/Table/Text.jsx, src/Table/__tests__/actions.js, src/Table/__tests__/reducers/history.js, src/Table/__tests__/tableReducer.js, src/Table/actions.js, src/Table/reducers/history.js, src/Table/tableReducer.js, src/components/TableWithPaste/__test__/TableWithPasteContainer.spec.js, src/components/TableWithPaste/containers/TableWithPasteContainer.js, src/components/TableWithPaste/containers/index.js, src/components/TableWithPaste/index.js, src/decorators/index.js, src/decorators/withPaste/__tests__/withPaste.spec.js, src/decorators/withPaste/index.js, src/decorators/withPaste/withPaste.js, src/export.js, src/utils/__tests__/utils.js, src/utils/index.js
https://jira.railsc.ru/browse/GOODS-1011
=> feature: добавит возможность вставки данных в таблицу из буфера

dist/app.bundle.js, dist/assets-table.bundle.js, src/Tree/TreeItem.jsx
https://jira.railsc.ru/browse/GOODS-1132
=> feature: ссылки для быстрых переходов между ЕТИ, ТИГР, ТиУ [skip ci]

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, package.json, src/decorators/withPaste/__tests__/withPaste.spec.js, src/decorators/withPaste/withPaste.js, yarn.lock
https://jira.railsc.ru/browse/GOODS-1145
=> feature: добавит возможность вставки многострочной ячейки

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/remove/sagas.js
Conflicts:
- dist/app.bundle.js
- dist/assets-help.bundle.js
- dist/assets-table.bundle.js
=>  Merge branch 'master' into tiger_ctrlv

dist/app.css, dist/assets-table.css, src/Tree/e-tree.scss
https://jira.railsc.ru/browse/GOODS-1077
=> fix: не раскрывается подгруппа при большом количестве вложений [skip ci]

dist/app.bundle.js, dist/assets-table.bundle.js, src/RemoveConfirmationDialog/RemoveConfirmationDialog.jsx, src/RemoveEmptyGroupsDialog/RemoveEmptyGroupsDialog.jsx, src/RemoveMassConfirmDialog/RemoveMassConfirmDialog.jsx, src/SaveControl/SaveControl.jsx, src/SaveControl/SaveControlContainer.jsx, src/SaveControl/actions.js, src/SaveControl/reducer.js, src/SaveControl/sagas.js, src/remove/reducer.js
https://jira.railsc.ru/browse/GOODS-1114
=> feature: изменения в строке состояния [skip ci]

dist/app.bundle.js, dist/assets-table.bundle.js, src/Table/rowReducer.js, src/decorators/withPaste/withPaste.js
1. Вставка в несохраненные ячейки
2. Вставка многострочных ячеек в windows
https://jira.railsc.ru/browse/GOODS-1011
=> fix: исправит ошибки при вставке данных в таблицу из буфера

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/ComboSelect/ComboSelect.jsx, src/components/Table/styles/table.scss, src/components/Table/views/SelectCellView.js
https://jira.railsc.ru/browse/GOODS-1115
=> fix: исправит выравнивание текста в селекте управления выводом фильтров

dist/app.css, dist/assets-table.css, src/components/Table/styles/table.scss
https://jira.railsc.ru/browse/GOODS-1073
=> fix: исправит ширину колонки "Показ фильтров"

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/ImageEditor/ImageEditor.jsx, src/components/ImageEditor/__tests__/PreviewImageView.spec.js, src/components/ImageEditor/__tests__/PreviewImagesBoxViews.spec.js, src/components/ImageEditor/propTypes/index.js, src/components/ImageEditor/styles/image-editor.scss, src/components/ImageEditor/views/PreviewImageView.js, src/components/ImageEditor/views/PreviewImagesBoxView.js, src/constants/imageEditor.js, src/reducers/__tests__/imageEditor.spec.js, src/reducers/imageEditor.js, src/sagas/__tests__/imageEditor.spec.js, src/sagas/imageEditor.js
1. Корректная обработка случая, когда у группы нет рекомендованных изображений
2. Корректное закрытие попапа
3. Валидация урла картинки
4. Затенение рекомендованных изображений, если у группы выбрана картинка
https://jira.railsc.ru/browse/GOODS-1100
=> fix: исправит ошибки в попапе выбора картинки группы

dist/app.bundle.js, dist/assets-table.bundle.js, src/DropDownMenu/DropDownMenu.jsx, src/_app.mock.js
https://jira.railsc.ru/browse/GOODS-1100
=> fix: исправит вывод текстовой зоны

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/DropDownMenu/DropDownMenu.jsx, src/ImageEditor/ImageEditor.jsx, src/ImageEditor/e-image-editor.scss, src/Tree/TreeItem.jsx, src/_app.mock.js
https://jira.railsc.ru/browse/GOODS-1194
=> fix: изменит стили для текcтовой зоны в попапе выбора картинки

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-help.css, src/Help/Help.jsx, src/Help/e-help.scss
https://jira.railsc.ru/browse/CK-1479
=> feat: add close icon for Help

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-help.css, package.json, src/Help/Help.jsx, src/Help/e-help.scss
No conflicts.
Выпустили в БЛ. Там пока что подключена не самая последняя версия. Одного фикса не хватает https://github.com/abak-press/apress-assets-table/compare/company_help...master?expand=1
=> Merge company_help into master & release 1.1.0

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/ImageEditor/ImageEditor.jsx, src/ImageEditor/views/ImageDialogBodyView.jsx, src/Table/Image.jsx, src/components/ImageEditor/styles/image-editor.scss
https://jira.railsc.ru/browse/GOODS-1083
исправит стили картинок в FF и IE
добавит лоадер при загрузке картинки перетаскиванием на строку
=> fix: загрузка изображений с помощью перетаскивания на строку [skip ci]

dist/app.bundle.js, dist/assets-table.bundle.js, src/Table/Body.jsx
https://jira.railsc.ru/browse/GOODS-1083
=> fix: удаление конкретной группы

_mock/table/data.json, src/SaveControl/sagas.js, src/Table/e-table.scss, src/Table/example.jsx
https://jira.railsc.ru/browse/GOODS-1246
=> feature: колонка "Пользовательский контент"

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css
https://jira.railsc.ru/browse/GOODS-1246
=> feature: колонка "Пользовательский контент", bundles

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/ComboSelect/e-select.scss, src/ImageEditor/e-image-editor.scss, src/ImageEditor/views/RecommendedImagesView.jsx, src/components/UrlField/styles/url-field.scss
https://jira.railsc.ru/browse/GOODS-1203
=> fix: правка стилей [skip ci]

dist/app.css, dist/assets-table.css, src/Table/e-table.scss
https://jira.railsc.ru/browse/GOODS-1249
=> fix: отображение попапа с скедитором у ячейки

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/SaveControl/sagas.js, src/Table/e-table.scss
[MINOR] Добавлена поддержа полей 'Краткое описание для фасетов' и 'Полное описание для фасетов'
https://jira.railsc.ru/browse/GOODS-1299
=> feature: добавит поля для фасет в группе

dist/app.css, dist/assets-table.css, src/ComboSelect/e-select.scss, src/components/Table/styles/table.scss
https://jira.railsc.ru/browse/GOODS-1203
=> fix: верстка пагинатора [skip ci]

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/Table/Table.jsx
https://jira.railsc.ru/browse/GOODS-1340
=> fix: отображение вертикального скролла у таблицы

README.md, src/Header/Header.jsx, src/Header/e-header.scss, src/Help/Help.jsx, src/Help/e-help.scss, src/styles/mixins/icons.scss
[MINOR]: Уберет дублирующую ссылку «На сайт», изменит верстку вкладки «Справка», небольшие правки стилей
https://jira.railsc.ru/browse/GOODS-1443
=> fix: правки дизайна товарных страниц [skip ci]

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/SaveControl/reducer.js, src/SaveControl/sagas.js, src/Table/Body.jsx, src/Table/actions.js, src/Table/example.jsx, src/Table/reducers/history.js, src/Table/rowReducer.js, src/Table/tableReducer.js, src/components/Table/containers/PopupProportiesCellContainer.js, src/components/Table/containers/index.js, src/components/Table/propTypes/index.js, src/components/Table/styles/table.scss, src/components/Table/views/PopupProportiesCellView.js, src/components/Table/views/ProportiesForm.js, src/components/Table/views/index.js, src/styles/mixins/icons.scss
https://jira.railsc.ru/browse/GOODS-1573
=> feature: добавит колонку "Габариты" [skip ci]

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/Table/Body.jsx, src/components/PseudoLink/views/PseudoLinkView.js, src/components/Table/propTypes/index.js, src/components/Table/views/PopupProportiesCellView.js, src/components/Table/views/ProportiesForm.js
https://jira.railsc.ru/browse/GOODS-1463
=> feature(tiger): колонка "Габариты" правки после теста [skip ci]

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/App/style.scss, src/Table/Body.jsx, src/Table/Table.jsx, src/Table/e-table.scss
https://jira.railsc.ru/browse/GOODS-1905
Этот ПР связан с этим https://github.com/abak-press/apress-tiger/pull/207
=> fix: proper table overflow behavior

dist/app.css, dist/assets-table.css, package.json, src/Table/e-table.scss, src/Tree/e-tree.scss
https://jira.railsc.ru/browse/GOODS-2010
=> fix: nested e-tree-item padding fix

dist/app.bundle.js, dist/assets-table.bundle.js, package.json, src/Tree/TreeItem.jsx
https://jira.railsc.ru/browse/GOODS-2062
=> hotfix: empty e-tree-title 78 chrome bug

dist/app.bundle.js, dist/assets-table.bundle.js, package.json, src/Tree/TreeItem.jsx
https://jira.railsc.ru/browse/GOODS-2062
=> Merge goods-2062 into master

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/Table/e-table.scss, src/components/Table/containers/TextCellEditor.js
https://jira.railsc.ru/browse/GOODS-2010
=> fix: ck editor full visibility

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/Tree/ContainerTree.jsx, src/Tree/reducer.js, src/Tree/sagas.jsx, src/Tree/styles/e-tree.scss
https://jira.railsc.ru/browse/GOODS-2648
=> feat: add rubricator filter

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/Tree/ContainerTree.jsx, src/Tree/Tree.jsx, src/Tree/import.js
https://jira.railsc.ru/browse/GOODS-2645
=> feat: show save status for tree nodes moving

dist/app.bundle.js, dist/assets-table.bundle.js, src/Tree/ContainerTree.jsx, src/Tree/Tree.jsx, src/Tree/TreeItem.jsx, src/Tree/reducer.js, src/Tree/sagas.jsx
https://jira.railsc.ru/browse/GOODS-2648
=> fix: save tree filter in session storage

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/Button/e-button.scss, src/Dialog/example.js, src/Dialog/rc-dialog.scss
https://jira.railsc.ru/browse/GOODS-2623
=> feat: tiger popups redesign

dist/app.bundle.js, dist/app.css, dist/assets-help.bundle.js, dist/assets-table.bundle.js, dist/assets-table.css, src/OptionElement/CheckboxElement.jsx, src/PaymentDeliveryPopup/PaymentDeliveryPopup.jsx, src/PaymentDeliveryPopup/e-payment-delivery-popup.scss, src/Table/PaymentDelivery.jsx
https://jira.railsc.ru/browse/GOODS-2614
=> fix: delivery and payment text and popup fixes

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/Dialog/rc-dialog.scss
https://jira.railsc.ru/browse/GOODS-2623
=> fix: remove popups border radius and replace popups buttons

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/PaymentDeliveryPopup/PaymentDeliveryPopup.jsx, src/PaymentDeliveryPopup/actions.js, src/PaymentDeliveryPopup/e-payment-delivery-popup.scss, src/PaymentDeliveryPopup/reducers.js, src/Table/PaymentDelivery.jsx, yarn.lock
https://jira.railsc.ru/browse/GOODS-2614
=> fix: payment delivery popup animations and titles

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/Dialog/rc-dialog.scss, src/ImageEditor/views/ImageDialogFooterView.jsx, src/PaymentDeliveryPopup/e-payment-delivery-popup.scss, src/RemoveConfirmationDialog/RemoveConfirmationDialog.jsx, src/RemoveMassConfirmDialog/RemoveMassConfirmDialog.jsx
https://jira.railsc.ru/browse/GOODS-2623
=> fix: all popups text and design fixes

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/Dialog/rc-dialog.scss, src/Header/Header.jsx, src/Table/PaymentDelivery.jsx, src/Table/styles/e-table.scss
https://jira.railsc.ru/browse/GOODS-2614
https://jira.railsc.ru/browse/GOODS-2623
=> fix: payment and delivery cell overflow fix

dist/app.bundle.js, dist/assets-help.bundle.js, dist/assets-table.bundle.js, src/Table/Header.jsx
https://jira.railsc.ru/browse/GOODS-2679
=> fix: correct titles in table filters

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css, src/PaymentDeliveryPopup/PaymentDeliveryPopup.jsx, src/PaymentDeliveryPopup/e-payment-delivery-popup.scss
https://jira.railsc.ru/browse/GOODS-2717
=> fix: payment delivery redesign fixes

src/PaymentDeliveryPopup/PaymentDeliveryPopup.jsx, src/PaymentDeliveryPopup/e-payment-delivery-popup.scss
https://jira.railsc.ru/browse/GOODS-2717
=> fix: payment delivery popups correct group title and sizes

dist/app.bundle.js, dist/app.css, dist/assets-table.bundle.js, dist/assets-table.css
https://jira.railsc.ru/browse/GOODS-2717
=> chore: update assets table build
